// kafka-metrics/build.gradle
// Subproject specific configurations.
// Most configurations are inherited from the root project.

plugins {
    id 'java-library'
}

dependencies {
    // Spring Boot Actuator for Micrometer metrics
    // org.springframework.kafka:spring-kafka is inherited from the root project
    api 'org.springframework.boot:spring-boot-starter-actuator'
    api 'io.micrometer:micrometer-registry-cloudwatch2'
}

// This module is a library, not a runnable Spring Boot application.
// Disable the bootJar task for this module.
bootJar {
    enabled = false
}

// Optionally, if you want to produce a standard JAR (not an executable Spring Boot JAR):
jar {
    enabled = true
} 