// kafka-metrics/build.gradle
// Subproject specific configurations.
// Most configurations are inherited from the root project.

plugins {
    id 'java-library'
}

dependencies {
    api 'io.micrometer:micrometer-registry-cloudwatch2'
    
    // Add configuration processor for @ConfigurationProperties
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

// This module is a library, not a runnable Spring Boot application.
// Disable the bootJar task for this module.
bootJar {
    enabled = false
}

// Optionally, if you want to produce a standard JAR (not an executable Spring Boot JAR):
jar {
    enabled = true
} 